"""The job record, and the payload envelope this SDK reads and writes.

Payload shape
=============
``jobs.payload`` is a JSONB column. This SDK stores an *envelope* in it::

    {
        "handler": "emails.send_welcome",
        "payload": {"user_id": 42}
    }

``handler`` is the non-empty routing string you pass to ``Client.enqueue``.
``payload`` is your data, stored exactly as given — any JSON value, though an
object is the useful case. Nothing else is added; there are exactly two keys.

The handler lives here rather than in a column of its own because the queue has
no handler column, and inventing one would widen the contract between this SDK
and the queue's schema for something only the SDK uses. The envelope is a shape
the SDK owns end to end.

Reading back, ``unwrap`` reverses this when the object has exactly those two
keys and ``handler`` is a string. Anything else is passed through untouched as
``Job.payload`` with ``Job.handler is None`` — which is how rows written by the
queue's own ``conveyor.queue.enqueue`` come back, since those store the caller's
payload bare. A payload that happens to be shaped exactly like an envelope is
indistinguishable from one and will be unwrapped; the round trip is still
consistent, because that is precisely the payload an enqueue of it would write.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Literal

type JSONValue = None | bool | int | float | str | list[JSONValue] | dict[str, JSONValue]
"""Anything ``json.dumps`` accepts. Payloads are JSONB; they are not pickles."""

JobStatus = Literal["queued", "running", "succeeded", "dead", "cancelled"]
"""The states in ``db/schema.sql``'s ``job_status`` enum.

Deliberately a ``Literal`` and not an enum class: ``Job.status`` holds the raw
string from the database, so a status added to the queue later flows through
this SDK instead of blowing up in the row mapper. Type checkers still catch a
misspelled comparison at the call site, which is where the mistakes are.
"""

_ENVELOPE_KEYS = frozenset({"handler", "payload"})


def wrap(handler: str, payload: JSONValue) -> dict[str, JSONValue]:
    """Build the envelope written to ``jobs.payload``."""
    return {"handler": handler, "payload": payload}


def unwrap(raw: Any) -> tuple[str | None, Any]:
    """Split a stored payload into ``(handler, payload)``.

    Returns ``(None, raw)`` for anything that is not one of our envelopes, so a
    row written directly against the table is still readable.
    """
    if (
        isinstance(raw, dict)
        and _ENVELOPE_KEYS == raw.keys()
        and isinstance(raw.get("handler"), str)
    ):
        return raw["handler"], raw["payload"]
    return None, raw


@dataclass(frozen=True, slots=True)
class Job:
    """One row of ``jobs``, with the envelope already unpacked.

    Frozen because it is a snapshot: it reflects the row at the moment it was
    read, and the queue mutates rows constantly underneath you. Call ``get`` for
    a fresh one rather than expecting an instance to track the database.
    """

    id: int
    handler: str | None
    """``None`` for a job not enqueued through this SDK. See the module docstring."""
    payload: Any
    """Your data, unwrapped. Typed ``Any`` because JSONB round-trips arbitrary JSON."""
    status: JobStatus
    idempotency_key: str
    """The dedup key. Randomly generated by the database when you did not supply one."""
    attempts: int
    """Incremented when a worker *claims* the job, so an attempt that dies silently counts."""
    max_attempts: int
    run_at: datetime
    """Earliest time the job may be claimed. Retry backoff pushes this forward."""
    last_error: str | None
    created_at: datetime
    updated_at: datetime
    finished_at: datetime | None

    @property
    def is_terminal(self) -> bool:
        """True once the queue is done with this job, whatever the outcome."""
        return self.status in ("succeeded", "dead", "cancelled")

    @classmethod
    def _from_row(cls, row: dict[str, Any]) -> Job:
        handler, payload = unwrap(row["payload"])
        return cls(
            id=row["id"],
            handler=handler,
            payload=payload,
            status=row["status"],
            idempotency_key=row["idempotency_key"],
            attempts=row["attempts"],
            max_attempts=row["max_attempts"],
            run_at=row["run_at"],
            last_error=row["last_error"],
            created_at=row["created_at"],
            updated_at=row["updated_at"],
            finished_at=row["finished_at"],
        )
